### ISSUE TITLE
Create project's packages

### ISSUE THREAD

**Issue by fabiopagoti** [ABAP-Games/Elifoot#1]
Create both packages according to the guideline:

https://github.com/ABAP-Games/Elifoot/wiki/Developer-Guide#package-structure

**Comment by matheuscfontes** [comment]
#Question

Qual o nome do Pacote Fabio?

Att,

**Comment by fabiopagoti** [comment]
The package name is described in the wiki inside the link above.

Cheers,

**Comment by matheuscfontes** [comment]
#development

Packpage created!
