### ISSUE TITLE
Create Elifoot Team Class

### ISSUE THREAD

**Issue by matheuscfontes** [ABAP-Games/Elifoot#3]
Create class according with the wiki page

https://github.com/ABAP-Games/Elifoot/wiki/Soccer-Team

**Comment by fabiopagoti** [comment]
Class "ZCL_EF_TEAM" created in the local package while #1 is not completed.

Wiki page was adjusted according with code.

**Comment by matheuscfontes** [comment]
The class ZCL_EF_TEAM was created.
